#!/usr/bin/env python3
"""
Module for collecting random numbers generated by async_generator using async comprehension.
"""

from typing import List
async_generator = __import__('0-async_generator').async_generator

async def async_comprehension() -> List[float]:
    """
    Collects 10 random floats generated by async_generator using async comprehension.
    Returns:
        List[float]: A list containing 10 random float numbers.
    """
    return [num async for num in async_generator()]
